export const MCP_SERVERS = [
  {
    id: 'filesystem',
    name: 'Filesystem',
    category: 'File System',
    icon: '📁',
    description: 'Read, write, and manage files on your system',
    eli5: 'Lets the AI read and write files on your computer safely.',
    complex: 'Provides sandboxed filesystem access with configurable root directories, read/write permissions, and path restrictions.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-filesystem', '/path/to/allowed/dir'],
    env: {},
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'APIs',
    icon: '🐙',
    description: 'Interact with GitHub repositories, issues, and PRs',
    eli5: 'Connects the AI to GitHub so it can manage your code projects.',
    complex: 'Full GitHub API integration for repository management, issue tracking, PR operations, and code search via personal access token.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-github'],
    env: { GITHUB_PERSONAL_ACCESS_TOKEN: '' },
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    category: 'Database',
    icon: '🐘',
    description: 'Query and manage PostgreSQL databases',
    eli5: 'Lets the AI talk to your PostgreSQL database to read and write data.',
    complex: 'PostgreSQL database integration with query execution, schema inspection, migration support, and parameterized query safety.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-postgres', 'postgresql://localhost/mydb'],
    env: {},
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    category: 'Database',
    icon: '💾',
    description: 'Query and manage SQLite databases',
    eli5: 'Lets the AI work with simple local databases stored in files.',
    complex: 'SQLite database access with full SQL support, schema management, and WAL mode for concurrent read operations.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sqlite', '/path/to/db.sqlite'],
    env: {},
  },
  {
    id: 'puppeteer',
    name: 'Puppeteer Browser',
    category: 'Browser',
    icon: '🌐',
    description: 'Control a web browser for automation and testing',
    eli5: 'Gives the AI control of a web browser to test websites and automate tasks.',
    complex: 'Headless Chromium browser automation via Puppeteer for web scraping, E2E testing, screenshot capture, and DOM interaction.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-puppeteer'],
    env: {},
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    category: 'Search',
    icon: '🔍',
    description: 'Search the web using Brave Search API',
    eli5: 'Lets the AI search the internet using Brave Search.',
    complex: 'Web search integration via Brave Search API with result filtering, safe search, and structured result extraction.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-brave-search'],
    env: { BRAVE_API_KEY: '' },
  },
  {
    id: 'memory',
    name: 'Memory Server',
    category: 'Memory',
    icon: '🧠',
    description: 'Persistent memory storage for AI conversations',
    eli5: 'Gives the AI a long-term memory that persists between sessions.',
    complex: 'Knowledge graph-based persistent memory with entity storage, relationship tracking, and semantic retrieval for cross-session context.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-memory'],
    env: {},
  },
  {
    id: 'sequential-thinking',
    name: 'Sequential Thinking',
    category: 'Tools',
    icon: '🤔',
    description: 'Step-by-step reasoning and problem decomposition',
    eli5: 'Helps the AI think through problems one step at a time.',
    complex: 'Chain-of-thought reasoning server enabling structured multi-step problem decomposition with intermediate validation.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-sequential-thinking'],
    env: {},
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'APIs',
    icon: '💬',
    description: 'Send messages and interact with Slack workspaces',
    eli5: 'Connects the AI to Slack so it can send messages and read channels.',
    complex: 'Slack workspace integration with channel messaging, thread management, user lookup, and file sharing via Bot token.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-slack'],
    env: { SLACK_BOT_TOKEN: '', SLACK_TEAM_ID: '' },
  },
  {
    id: 'everything',
    name: 'Everything Search',
    category: 'Search',
    icon: '🔎',
    description: 'Instant file search across your entire system',
    eli5: 'Super fast file search that finds any file on your computer instantly.',
    complex: 'Integration with Everything search engine for instant filename search across all indexed drives with regex and path filtering.',
    command: 'npx',
    args: ['-y', '@modelcontextprotocol/server-everything'],
    env: {},
  },
];

export const MCP_CATEGORIES = [...new Set(MCP_SERVERS.map(s => s.category))].sort();

export function getMCPServersByCategory(category) {
  return MCP_SERVERS.filter(s => s.category === category);
}

export function getMCPServerById(id) {
  return MCP_SERVERS.find(s => s.id === id);
}
