export const PLUGIN_PACKS = [
  {
    id: 'starter-pack',
    name: 'Starter Pack',
    icon: '🎯',
    description: 'Essential ruflo setup for getting started',
    eli5: 'Everything you need to get started with ruflo. Installs the basics so you can start using AI agents right away.',
    complex: 'Core ruflo components including AgentDB persistence, Claude provider integration, and basic memory backend. Provides the foundation for all other packs.',
    includedAddons: ['agentdb-persistence', 'claude-provider', 'memory-consolidation'],
    installCommand: 'npx ruflo@latest install-pack starter',
    estimatedTime: '2-3 minutes',
    recommended: true,
  },
  {
    id: 'developer-pack',
    name: 'Developer Pack',
    icon: '👨‍💻',
    description: 'Git hooks, code review, and TDD workflow tools',
    eli5: 'Tools for developers who want the AI to help with git, code reviews, and testing.',
    complex: 'Comprehensive development toolkit with GitHub integration for PR management, automated code review, TDD workflow support, and CI/CD pipeline integration.',
    includedAddons: ['github-integration', 'agentdb-persistence', 'token-optimizer'],
    installCommand: 'npx ruflo@latest install-pack developer',
    estimatedTime: '3-4 minutes',
    recommended: false,
  },
  {
    id: 'security-pack',
    name: 'Security Pack',
    icon: '🔐',
    description: 'CVE scanning, threat modeling, and vulnerability detection',
    eli5: 'Makes your AI setup super secure with automatic scanning and protection against attacks.',
    complex: 'Full security suite including AIDefence for adversarial detection, CVE database scanning, STRIDE threat modeling, runtime monitoring, and syscall filtering.',
    includedAddons: ['security-suite-aidefence', 'agentdb-persistence'],
    installCommand: 'npx ruflo@latest install-pack security',
    estimatedTime: '2-3 minutes',
    recommended: false,
  },
  {
    id: 'ai-power-pack',
    name: 'AI Power Pack',
    icon: '🧠',
    description: 'Neural attention, reinforcement learning, and advanced memory',
    eli5: 'Makes your AI agents way smarter with advanced learning and memory capabilities.',
    complex: 'Advanced AI capabilities with RuVector Intelligence (SONA, EWC++, Flash Attention), reinforcement learning algorithms (PPO, A2C, DQN, DDPG), and long-term memory consolidation with knowledge graphs.',
    includedAddons: ['ruvector-intelligence', 'reinforcement-learning', 'memory-consolidation', 'hnsw-vector-search'],
    installCommand: 'npx ruflo@latest install-pack ai-power',
    estimatedTime: '4-5 minutes',
    recommended: false,
  },
  {
    id: 'performance-pack',
    name: 'Performance Pack',
    icon: '⚡',
    description: 'WASM acceleration, token optimization, and background workers',
    eli5: 'Makes everything faster and cheaper - speeds up the AI and saves you money on API calls.',
    complex: 'Performance optimization suite with WebAssembly acceleration for compute-intensive tasks, intelligent token budgeting for cost reduction, and 12 background worker types for async processing.',
    includedAddons: ['agent-booster-wasm', 'token-optimizer', 'background-workers'],
    installCommand: 'npx ruflo@latest install-pack performance',
    estimatedTime: '3-4 minutes',
    recommended: false,
  },
  {
    id: 'multi-model-pack',
    name: 'Multi-Model Pack',
    icon: '🌐',
    description: 'All LLM providers - Claude, GPT, Gemini, and Ollama',
    eli5: 'Use any AI model you want - Claude, GPT, Gemini, or even run models locally on your computer.',
    complex: 'Complete LLM provider suite enabling model routing across Anthropic Claude, OpenAI GPT, Google Gemini, and local Ollama models with intelligent fallback and load balancing.',
    includedAddons: ['claude-provider', 'gpt-provider', 'gemini-provider', 'ollama-provider'],
    installCommand: 'npx ruflo@latest install-pack multi-model',
    estimatedTime: '3-4 minutes',
    recommended: false,
  },
  {
    id: 'full-stack-pack',
    name: 'Full Stack Pack',
    icon: '🏗️',
    description: 'Everything - all addons and capabilities in one install',
    eli5: 'Install EVERYTHING at once. Get all the features ruflo has to offer in one click.',
    complex: 'Complete ruflo installation including all intelligence, persistence, search, provider, performance, security, integration, worker, and learning components.',
    includedAddons: ['ruvector-intelligence', 'agentdb-persistence', 'hnsw-vector-search', 'claude-provider', 'gpt-provider', 'gemini-provider', 'ollama-provider', 'agent-booster-wasm', 'token-optimizer', 'security-suite-aidefence', 'github-integration', 'background-workers', 'reinforcement-learning', 'memory-consolidation'],
    installCommand: 'npx ruflo@latest install-pack full',
    estimatedTime: '8-10 minutes',
    recommended: false,
  },
];

export function getPackById(id) {
  return PLUGIN_PACKS.find(p => p.id === id);
}
